development:
  adapter: postgresql
  encoding: unicode
  database: boulder_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: boulder_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: boulder_production
  pool: 5
  username: boulder
  password:
